### ISSUE TITLE
Error when compiling for a STM32F103C8T6

### ISSUE THREAD

**Issue by ClashC** [mathertel/Radio#12]
Error is posted here:
http://pastebin.com/nD5tX9D9

Note: With the library "FMRM1" from the company ELV the Si4705 FM module "FM-RM1" works. 
I like your library very much.

**Comment by ClashC** [comment]
Note: With the library "FMRM1" from the company ELV the Si4705 FM module "FM-RM1" works.

**Comment by ClashC** [comment]
Hell Matthias.
I have remove the Files:
newchip.*
RDA5807M.*
TEA5767.*

and add "#include <stdarg.h>" in radio.h after #include <Wire.h>. Otherwise the error comes Error:
"'va_list' was not declared in this scope".

Now works the Library for FMRM1. :)

**Comment by mathertel** [comment]
Thanks a lot for the hints.
