### ISSUE TITLE
Where is the actual register access code?

### ISSUE THREAD

**Issue by cgrund1** [mathertel/Radio#19]
Forgive my poor grasp of how include files work. I have been successfully including and using the radio.h and RDA5807M.h files with my project (Arduino Nano drives 3 FM radios, and reads back RSSI info to select best signal for audio output). For speed, I would like to directly read/write  single RDA registers , and got very confused reading the RDA spec sheet. So I tried to use the *.h files for examples of how to do this, but don't understand how to find the actual low level code that does the register communication.      I see a lines like this:

// ----- combined status functions -----
  183   virtual void getRadioInfo(RADIO_INFO *info); 

I am successfully using getRadioInfo() using a pointer to the structure, but can't find the actual function code. Also would like to set or read some items not defined in the *.h files. Can anyone point me to  where the actual register access code is?
Thanks,  Chris

**Comment by mathertel** [comment]
The getRadioInfo implementation can be found in src\RDA5807M.cpp.
