### ISSUE TITLE
Hint for RDSParser.cpp

### ISSUE THREAD

**Issue by ClashC** [mathertel/Radio#2]
Hello Matthias,
Thank you for the very nice Library. I have the ELVRADIO and testing the RDSText.
In RDSTEXT it will replace characters with ']', but no Errors.
I comment out the two lines in rdsparser.cpp

// p = strchr(_RDSText, '\0x0D');
// if (p) *p = ']';

Now, have i text without ']'.

The accuracy of the RDSTEXT and the Stationname like it. (si4705)
Is it so exactly at the si4703?

ClashC

**Comment by mathertel** [comment]
you are right. fixed today by removing These lines.
