### ISSUE TITLE
'va_list' error

### ISSUE THREAD

**Issue by hydronics2** [mathertel/Radio#22]
This error was already called out by cashC in 2016. Same error for me with An Adafruit M0 board for an RDA5807m.... adding the stdarg.h in radio.h  fixed the error per below comment... thank you!

 add "#include <stdarg.h>" in radio.h after #include <Wire.h>. Otherwise the error comes Error:
"'va_list' was not declared in this scope".

**Comment by mathertel** [comment]
version 3.0.x fixed a lot. compiles again.
