### ISSUE TITLE
webradio webserver doesn't start

### ISSUE THREAD

**Issue by onurguc** [mathertel/Radio#24]
Hi,

I'm receiving errors like below.  The ethernet shield seems to work but then the webserver doesn't start.  I put the 3 web files on SD card without any additional directory.  Not sure what I'm doing wrong.

12:19:04.656 -> >setFrequency(10000)
12:19:04.656 -> >_waitEnd()
12:19:04.732 -> >setMono(0)
12:19:04.767 -> >setMute(0)
12:19:04.767 -> >setVolume(6)
12:19:06.002 -> >Ethernet Result:1
12:19:06.002 -> >Configuration:
12:19:06.002 -> > localIP:192.168.3.109
12:19:06.002 -> > subnetMask:255.255.255.0
12:19:06.002 -> > dnsServerIP:192.168.3.1
12:19:06.002 -> > gatewayIP:192.168.3.1
12:19:06.002 -> >Starting the server...
12:19:06.002 -> >Free RAM:4153
12:19:06.002 -> 12850
12:19:06.002 -> >RDS:        
12:19:06.035 -> >FREQ:100.00 MHz
12:19:06.281 -> >RDS:POWER FM
12:19:09.520 -> >RDS-text:
12:19:15.578 -> >RDS:POWER P⸮
12:19:15.890 -> >RDS-text:EN IYI EN YENI MUZIK                        
12:19:15.998 -> >RDS:POWER FM
12:19:16.356 -> 62282
12:19:16.427 -> 12850
12:19:17.912 -> >RDS-text:
12:19:26.314 -> >RDS-text:EN IYI EN YENI MUZIK
12:19:34.732 -> >RDS-text:EN IYI EN YENI MUZIK            
12:19:43.131 -> >RDS-text:EN IYI EN YENI MUZIK                                            
12:19:48.830 -> >RDS:POWER PO
12:19:49.180 -> >RDS:POWER FM
12:19:51.547 -> >RDS-text:EN IYI EN YENI MUZIK                                            
12:19:58.640 -> >RDS-time:12:20
12:20:00.049 -> >RDS-text:EN IYI EN YENI MUZIK                                            
12:20:08.451 -> >RDS-text:EN IYI EN YENI MUZIK                                            
12:20:09.670 -> >respond404NotFound()

Any thoughts?

**Comment by mathertel** [comment]
Please re-check.
