### ISSUE TITLE
Changing version in library.properties 

### ISSUE THREAD

**Issue by roboticboyer** [mathertel/Radio#26]
It's required changing version in library.properties so the Arduino Library Manager Bot will update the Arduino libraries repository

[link](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-publish-a-new-release-once-my-library-is-in-the-list)

Thank you
Gio

_Originally posted by @roboticboyer in https://github.com/mathertel/Radio/issues/25#issuecomment-504173871_

**Comment by mathertel** [comment]
should be correct now for version 1.2.0
