### ISSUE TITLE
Volume not working

### ISSUE THREAD

**Issue by sn4k3** [mathertel/Radio#3]
Hello,

I find this library great! Still i can't get volume to work with your demo serial or fixed...
Im using a TEA5767 but not the simple one, im using this one: http://i.ebayimg.com/00/s/NzY4WDEwMjQ=/z/X18AAOSwPhdVDcz0/$_57.JPG

Does volume should work this this module?

**Comment by mathertel** [comment]
Hi Tiago,

 

The TEA5767 doesn’t have any volume control inside and the audio output is always full speed or mute.

I guess that the other chip on that Breakout is a TDA1308. This amplifier cannot be volume controlled.

So: NO.

 

Regards, Matthias

 

Von: Tiago Conceição [mailto:notifications@github.com] 
Gesendet: Donnerstag, 16. Juli 2015 03:26
An: mathertel/Radio
Betreff: [Radio] Volume not working (#3)

 

Hello,

I find this library great! Still i can't get volume to work with your demo serial or fixed...
Im using a TEA5767 but not the simple one, im using this one: http://i.ebayimg.com/00/s/NzY4WDEwMjQ=/z/X18AAOSwPhdVDcz0/$_57.JPG <http://i.ebayimg.com/00/s/NzY4WDEwMjQ=/z/X18AAOSwPhdVDcz0/%24_57.JPG> 

Does volume should work this this module?

**Comment by sn4k3** [comment]
Hi,

So there are any radio module with volume control? What do you recommend?
Maybe i can modify the TEA5767 and add a Digital Potentiometer to control de output?

Thanks

**Comment by nikolisan** [comment]
Hi Thiago, I'm using a SI4703 breakout board I've found cheap on ebay. It has volume control and RDS. If you ensist on using the TEA5767 you can make your own amplifier and adjust the volume from there with a digital or analog pot. Search on google and you'll find many instructables.

**Comment by sn4k3** [comment]
Hello, i solve it with a digital pot some month ago :)
Thanks

**Comment by nikolisan** [comment]
Glad to hear that! May I ask how? You used TEA5767?

**Comment by sn4k3** [comment]
Sure, check this schemenatic: https://github.com/sn4k3/LedClock/blob/master/Eagle/ledclock_schemantic.png
I used DS1803 digital 100K Pot

**Comment by sn4k3** [comment]
And: https://github.com/sn4k3/LedClock/blob/master/Arduino/RadioFM.cpp
