### ISSUE TITLE
Porting for 8266

### ISSUE THREAD

**Issue by wotipka** [mathertel/Radio#36]
Having a hard time locating where the I2C address is set and where the pins are specified.   Using the RDA5807 chip and NodeMCU.

**Comment by mathertel** [comment]
These are ESP8266 specific problems. ESP8266 has no fixed pins for I2C as it is emulated in software and not hardware based.
The library compiles well in ESP8266 and I use it in a ESP8266 project.

**Comment by mathertel** [comment]
Some examples now have some code to explicitly initialize the esp8266 i2c/wire bus and library.
