### ISSUE TITLE
declaration   typedef struct AUDIO_INFO

### ISSUE THREAD

**Issue by fungreenfox** [mathertel/Radio#42]
\libraries\Radio-master\src/radio.h:128:1: warning: 'typedef' was ignored in this declaration

 typedef struct AUDIO_INFO {

 ^~~~~~~

How to get around this warning?

**Comment by Galaadan** [comment]
Hi 
It's a problem with typedef syntaxe
the right is "typedef struct { ....} typename;"
then in the code the rigth is typedef struct { ...} AUDIO_INFO;

**Comment by mathertel** [comment]
was fixed in 3.0.0
