### ISSUE TITLE
Rda5807 Lcd radio 

### ISSUE THREAD

**Issue by debashis1989** [mathertel/Radio#48]
Dear Sir, I am working on your code it's really interesting. I am using your Lcdradio library. My connections including rda5807m, Arduino Uno, Two push buttons, rotary encoder and 16×2 lcd display with PCF8574. I did all the connection correctly with some minor modifications in code as per my set up. But I found rotary encoder and seek button function not working. Only menu button works. I changed the A10, A11 values to A0 and A1 and rotary encoder value to A2 and A3. Still the same issue. 
I really appreciate your work meanwhile i seek you help regarding this problem. 

Thanks

**Comment by mathertel** [comment]
The Rotary Library was extended to support more types of encoders.
Please use current version of Rotary Library and check.
