### ISSUE TITLE
Si7403 #define IN_EUROPE hardcoded

### ISSUE THREAD

**Issue by fjansson** [mathertel/Radio#59]
For Si4703, the region setting is hardcoded:
https://github.com/mathertel/Radio/blob/5772c7cda2ce4c58176d9eb688cae46af2579464/src/SI4703.cpp#L27
Would it be possible to make this configurable? The European spacing (100 kHz) is finer than the US spacing (200 kHz), so US stations can still be tuned. The  IN_EUROPE flag also applies the European de-emphasis setting of 50 us.

Related: would it be possible to support the Japanese FM band 76–95 MHz ?

**Comment by mathertel** [comment]
duplicate to #60
