### ISSUE TITLE
fail at bassboost

### ISSUE THREAD

**Issue by fungreenfox** [mathertel/Radio#67]
Only SI4703 is decleared in the script, however there are compiler warnings for SI4705:

Driveletter:\Arduino scripts\libraries\Radio\src\SI4705.cpp:229:34: error: variable or field 'setBassBoost' declared void
 void SI4705::setBassBoost(UNUSED bool switchOn) {
                                  ^
Driveletter:\Arduino scripts\libraries\Radio\src\SI4705.cpp:229:27: error: 'UNUSED' was not declared in this scope
 void SI4705::setBassBoost(UNUSED bool switchOn) {

**Comment by mathertel** [comment]
What processor are you using ?

**Comment by fungreenfox** [comment]
Esp32 Wroom 30 pins.
The problem has disappeared though.

**Comment by fungreenfox** [comment]
However, when the volume is turned upwards / raised over 4 or 5 or so, the esp32 reboots. This happened only with the newer version of radio.h

**Comment by fungreenfox** [comment]
Solved the issue.
