### ISSUE TITLE
(RT+) RadioText + 

### ISSUE THREAD

**Issue by Stavr0s13** [mathertel/Radio#7]
Hey, Thanks for the good work you have done here, Just wanted to ask if there is a radio text plus support on this library. Thanks again!

**Comment by mathertel** [comment]
in the current version there is no radio text plus support, only regular radio text.
However the data stream is available and only some decoding rules have to be implemented.
Maybe later or someone else ?

**Comment by Stavr0s13** [comment]
I would love to try decoding it, but i can't find how the RT+ works. Is there any place i can find something?
