### ISSUE TITLE
SNR and CNT functions not working with Si4703

### ISSUE THREAD

**Issue by heisenberg1995** [mathertel/Radio#9]
Hi,
Thanks for the great library! I am using an Si4703 with an Arduino Uno. The RSSI functionality works great but there seems to be a problem with the SNR. It always shows 0. Have you disabled it by any chance? If yes, how do you enable it? I would also appreciate if you could tell me how to access the SKCNT data.

**Comment by fungreenfox** [comment]
Same for this Si4703 (not breakout version). SNR is always 0.

**Comment by fungreenfox** [comment]
There is an unwanted sign after "void".

**Comment by mathertel** [comment]
SI4703 doesn't support reading the SNR via I2C.
AS of the manual it is used internally while scanning only.
